import { useEffect, useRef } from 'react';
import { useNavigate, useParams, useSearchParams } from 'react-router-dom';
import { Button } from '../../components/Button';
import { Container, SectionHeading } from '../../components/Section';
import { ErrorState } from '../../components/StateFeedback';
import { useCharacter } from '../../hooks/useCharacters';
import { usePlaylistGeneration, useSavePlaylist } from '../../hooks/usePlaylistActions';
import CharacterInfoPanel from './components/CharacterInfoPanel';
import PlaylistResultCard from './components/PlaylistResultCard';

const DetailSkeleton = () => (
  <div className="grid animate-pulse gap-6 rounded-2xl border border-neutral bg-white p-6 md:grid-cols-[240px_1fr]">
    <div className="h-[240px] rounded-xl bg-neutral" />
    <div className="flex flex-col gap-4">
      <div className="h-7 w-1/3 rounded bg-neutral" />
      <div className="h-4 w-full rounded bg-neutral" />
      <div className="h-4 w-5/6 rounded bg-neutral" />
      <div className="h-4 w-2/3 rounded bg-neutral" />
    </div>
  </div>
);

const PlaylistSkeleton = ({ regenerating = false }: { regenerating?: boolean }) => (
  <div className="flex flex-col gap-3 rounded-2xl bg-primary p-6">
    <h4 className="text-body font-semibold">
      {regenerating
        ? 'Buscando nuevas canciones...'
        : 'Descubriendo su personalidad y poderes...'}
    </h4>
    <p className="text-tags text-muted">
      {regenerating
        ? 'Renovando la selección en Spotify.'
        : 'Consultando a la IA y buscando su música.'}
    </p>

    <div className="mt-2 h-7 w-1/2 animate-pulse rounded bg-muted/40" />
    {[0, 1, 2].map((row) => (
      <div key={row} className="h-12 w-full animate-pulse rounded bg-muted/40" />
    ))}
  </div>
);

const CharacterDetailPage = () => {
  const { slug = '' } = useParams();
  const [searchParams] = useSearchParams();
  const navigate = useNavigate();
  const autoGenerate = searchParams.get('generate') === '1';

  const { data: character, loading, error, reload } = useCharacter(slug);
  const {
    playlist,
    loading: generating,
    error: generationError,
    generate,
    reset,
  } = usePlaylistGeneration();
  const { saving, saved, error: saveError, save } = useSavePlaylist();

  // Evita regenerar en cada render y evita la doble invocación de StrictMode.
  const autoGeneratedSlug = useRef<string | null>(null);

  // Al cambiar de personaje, limpiamos el estado de generación anterior.
  useEffect(() => {
    reset();
  }, [slug, reset]);

  useEffect(() => {
    if (!autoGenerate || !character) return;
    if (autoGeneratedSlug.current === character.slug) return;

    autoGeneratedSlug.current = character.slug;
    void generate(character.slug);
  }, [autoGenerate, character, generate]);

  if (loading) {
    return (
      <Container className="flex flex-col gap-8 py-8">
        <DetailSkeleton />
      </Container>
    );
  }

  if (error || !character) {
    return (
      <Container className="py-10">
        <ErrorState message={error ?? 'Personaje no encontrado'} onRetry={reload} />
      </Container>
    );
  }

  const handleSave = () => {
    if (!playlist) return;
    void save({
      heroId: playlist.character.slug,
      heroName: playlist.character.name,
      mood: playlist.mood,
      description: playlist.profile.summary,
      songs: playlist.songs,
    });
  };

  // Mientras llega el perfil (o si venimos con ?generate=1) se muestran
  // esqueletos en el panel, nunca la descripción oficial en inglés.
  const profilePending = !playlist && !generationError && (generating || autoGenerate);

  return (
    <Container className="flex flex-col gap-8 py-8">
      <SectionHeading>¡Conozcamos a {character.name}!</SectionHeading>

      <CharacterInfoPanel
        character={character}
        profile={playlist?.profile ?? null}
        loading={profilePending}
      />

      <div className="flex flex-col gap-3">
        <p className="text-secondary text-primary">
          Mientras descubres la ciudad suena esto en su cabeza...
        </p>

        {generating && <PlaylistSkeleton regenerating={Boolean(playlist)} />}

        {!generating && generationError && (
          <ErrorState
            title="No pudimos generar la playlist"
            message={generationError}
            onRetry={() => void generate(character.slug)}
          />
        )}

        {!generating && !generationError && playlist && (
          <PlaylistResultCard
            playlist={playlist}
            saving={saving}
            saved={saved}
            saveError={saveError}
            onSave={handleSave}
          />
        )}

        {!generating && !generationError && !playlist && (
          <Button
            label="Crear playlist"
            variant="success"
            icon="music"
            onClick={() => void generate(character.slug)}
            className="self-start"
          />
        )}
      </div>

      <div className="flex flex-wrap items-center justify-between gap-3">
        <Button
          label="Regresar"
          variant="outline"
          icon="arrow-left"
          onClick={() => navigate(-1)}
        />

        {playlist && (
          <Button
            label="Regenerar"
            variant="background"
            icon="rotate-right"
            onClick={() =>
              void generate(character.slug, {
                // Se reutiliza el perfil: solo se vuelven a buscar canciones.
                reuse: { profile: playlist.profile, vibes: playlist.vibes },
              })
            }
            loading={generating}
          />
        )}
      </div>
    </Container>
  );
};

export default CharacterDetailPage;
